### ISSUE TITLE
vagrant modify-instance ArgumentError

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/vagrant-openshift#388]
seen [here](https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/8993/console):
```
+ /usr/bin/vagrant modify-instance -r origin_test_pull_requests_origin_8994_terminate -s
/var/lib/jenkins/.vagrant.d/gems/gems/fog-1.26.0/lib/fog/aws/region_methods.rb:6:in `validate_aws_region': Unknown region: "<AMI_REGION>" (ArgumentError)
	from /var/lib/jenkins/.vagrant.d/gems/gems/fog-1.26.0/lib/fog/aws/compute.rb:476:in `initialize'
	from /var/lib/jenkins/.vagrant.d/gems/gems/fog-core-1.32.0/lib/fog/core/service.rb:115:in `new'
	from /var/lib/jenkins/.vagrant.d/gems/gems/fog-core-1.32.0/lib/fog/core/service.rb:115:in `new'
	from /var/lib/jenkins/.vagrant.d/gems/gems/fog-core-1.32.0/lib/fog/core/services_mixin.rb:16:in `new'
	from /var/lib/jenkins/.vagrant.d/gems/gems/fog-core-1.32.0/lib/fog/compute.rb:62:in `new'
	from /var/lib/jenkins/.vagrant.d/gems/gems/vagrant-aws-0.6.0/lib/vagrant-aws/action/connect_aws.rb:40:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builder.rb:116:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/runner.rb:66:in `block in run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/util/busy.rb:19:in `busy'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/runner.rb:66:in `run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/machine.rb:214:in `action_raw'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/machine.rb:191:in `block in action'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/environment.rb:516:in `lock'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/machine.rb:178:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/machine.rb:178:in `action'
	from /var/lib/jenkins/.vagrant.d/gems/gems/vagrant-aws-0.6.0/lib/vagrant-aws/provider.rb:32:in `state'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/machine.rb:490:in `state'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/machine.rb:141:in `initialize'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/vagrantfile.rb:79:in `new'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/vagrantfile.rb:79:in `machine'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/environment.rb:612:in `machine'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/plugin/v2/command.rb:168:in `block in with_target_vms'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/plugin/v2/command.rb:201:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/plugin/v2/command.rb:201:in `block in with_target_vms'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/plugin/v2/command.rb:200:in `map'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/plugin/v2/command.rb:200:in `with_target_vms'
	from /var/lib/jenkins/.vagrant.d/gems/gems/vagrant-openshift-3.0.3/lib/vagrant-openshift/command/modify_instance.rb:54:in `execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/cli.rb:42:in `execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/environment.rb:301:in `cli'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/bin/vagrant:174:in `<main>'
Build step 'Execute a set of scripts' marked build as failure
[BFA] Scanning build for known causes...
[BFA] No failure causes found
[BFA] Done. 0s
Finished: FAILURE
```

/cc @bparees @danmcp

**Comment by danmcp** [comment]
@stevekuznetsov That's a red herring.  The error is above: CONFLICT (content): Merge conflict in hack/test-cmd.sh

**Comment by stevekuznetsov** [comment]
@danmcp I don't disagree that the call to `modify-instance` was not in error, but why did that call fail?

**Comment by danmcp** [comment]
@stevekuznetsov It didn't get to creating the instance.  And it always trys to clean it up at the end.  I'll go ahead and try to fix.

**Comment by danmcp** [comment]
@stevekuznetsov Should be fixed
